// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql_model

import (
	"server/pkg/model"
)

type AuthPayload struct {
	Token *string     `json:"token,omitempty"`
	User  *model.User `json:"user,omitempty"`
}

type CreateCompanyInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}
