package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"
	"server/graph"
	"server/pkg/model"
)

// ID is the resolver for the id field.
func (r *companyResolver) ID(ctx context.Context, obj *model.Company) (string, error) {
	panic(fmt.Errorf("not implemented: ID - company"))
}

// Email is the resolver for the email field.
func (r *companyResolver) Email(ctx context.Context, obj *model.Company) (string, error) {
	panic(fmt.Errorf("not implemented: Email - email"))
}

// Company returns graph.CompanyResolver implementation.
func (r *Resolver) Company() graph.CompanyResolver { return &companyResolver{r} }

type companyResolver struct{ *Resolver }
