package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"errors"
	"server"
	"server/graph"
	gql_model "server/graph/model"
	"server/pkg/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input gql_model.CreateUserInput) (*model.User, error) {
	res, err := r.UserService.CreateUser(ctx, input)
	if err != nil {
		switch {
		case errors.Is(err, server.ErrValidation):
			return nil, buildBadRequestError(ctx, err)
		default:
			return nil, err
		}
	}
	return res, nil
}

// CreateCompany is the resolver for the createCompany field.
func (r *mutationResolver) CreateCompany(ctx context.Context, input gql_model.CreateCompanyInput) (*model.Company, error) {
	res, err := r.CompanyService.CreateCompany(ctx, input)
	if err != nil {
		switch {
		case errors.Is(err, server.ErrValidation):
			return nil, buildBadRequestError(ctx, err)
		default:
			return nil, err
		}
	}
	return res, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input gql_model.LoginInput) (*gql_model.AuthPayload, error) {
	res, err := r.AuthService.Login(ctx, gql_model.LoginInput{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		switch {
		case errors.Is(err, server.ErrValidation) ||
			errors.Is(err, server.ErrBadCredentials):
			return nil, buildError(ctx, err)
		default:
			return nil, err
		}
	}
	return mapAuthResponse(*res), nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
